/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleados;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author csuarez25
 */
public class interfaz extends javax.swing.JFrame {

    Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdentDir = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNombreDir = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtApellidoDir = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDirDir = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCorreoDir = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDepenDir = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtAntigDir = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtHTrabDir = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtValorHoraDir = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewDir = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        btnDir = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtCelDir = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreOpe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoOpe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdentOpe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDirOpe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreoOpe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAntigOpe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProfOpe = new javax.swing.JTextField();
        txtHTrabOpe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorOpe = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        labHE = new javax.swing.JLabel();
        txtDinamico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewOpe = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        btnOpe = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtCelOpe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nomina");
        setLocation(new java.awt.Point(300, 50));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Informacion del Directivo:");

        jLabel13.setText("Identificacion: ");

        txtIdentDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentDirActionPerformed(evt);
            }
        });
        txtIdentDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentDirKeyTyped(evt);
            }
        });

        jLabel14.setText("Nombre:");

        txtNombreDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDirActionPerformed(evt);
            }
        });
        txtNombreDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreDirKeyTyped(evt);
            }
        });

        jLabel15.setText("Apellido:");

        txtApellidoDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoDirKeyTyped(evt);
            }
        });

        jLabel16.setText("Dirrecion:");

        jLabel17.setText("Correo:");

        jLabel18.setText("Dependencia:");

        txtDepenDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDepenDirKeyTyped(evt);
            }
        });

        jLabel19.setText("Antiguedad(meses):");

        txtAntigDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAntigDirKeyTyped(evt);
            }
        });

        jLabel20.setText("Horas trabajadas:");

        txtHTrabDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHTrabDirKeyTyped(evt);
            }
        });

        jLabel21.setText("Valor hora:");

        txtValorHoraDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorHoraDirKeyTyped(evt);
            }
        });

        viewDir.setColumns(20);
        viewDir.setRows(5);
        viewDir.setVisible(false);
        jScrollPane2.setViewportView(viewDir);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Información generada: ");
        setVisible(false);

        btnDir.setText("Guardar");
        btnDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirActionPerformed(evt);
            }
        });

        jLabel25.setText("Celular:");

        txtCelDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelDirKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtIdentDir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtNombreDir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidoDir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtDirDir)
                    .addComponent(txtCorreoDir)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtValorHoraDir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDir))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCelDir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txtDepenDir)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAntigDir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txtHTrabDir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(11, 11, 11)
                        .addComponent(txtIdentDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDirDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreoDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepenDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAntigDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHTrabDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorHoraDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnDir))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Directivos", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Informacion del Operador:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Identificacion: ");

        txtIdentOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentOpeActionPerformed(evt);
            }
        });

        jLabel6.setText("Dirrecion:");

        jLabel7.setText("Correo:");

        jLabel8.setText("Antiguedad(meses):");

        jLabel9.setText("Profesion:");

        jLabel10.setText("Horas trabajadas:");

        jLabel11.setText("Valor hora:");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Selecciona Tipo-", "Tecnico 1", "Tecnico 2", "Tecnico 3", "Master" }));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });

        jLabel22.setText("Tipo de operario:");

        txtDinamico.setVisible(false);

        viewOpe.setColumns(20);
        viewOpe.setRows(5);
        viewOpe.setBorder(null);
        viewOpe.setVisible(false);
        jScrollPane1.setViewportView(viewOpe);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Información generada: ");

        btnOpe.setText("Guardar");
        btnOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpeActionPerformed(evt);
            }
        });

        jLabel26.setText("Celular: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNombreOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel5)
                            .addComponent(txtIdentOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(txtCorreoOpe)
                            .addComponent(txtDirOpe)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProfOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHTrabOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnOpe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCelOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(txtAntigOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labHE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValorOpe, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDinamico)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdentOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDirOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreoOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAntigOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProfOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHTrabOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labHE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpe)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Operadores", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SIGGO Nomina express");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/certificado (2).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentDirActionPerformed

    private void txtNombreDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDirActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed

        if (cbxTipo.getSelectedIndex() == 1 || cbxTipo.getSelectedIndex() == 2) {
            labHE.setText("Especialidad:");
            txtDinamico.show();
        } else if (cbxTipo.getSelectedIndex() == 3 || cbxTipo.getSelectedIndex() == 4) {
            labHE.setText("Horas extras:");
            txtDinamico.show();
        }
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void txtIdentOpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentOpeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentOpeActionPerformed

    private void btnDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirActionPerformed
        if (txtIdentDir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, verificar el campo de identificación", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (txtNombreDir.getText().isEmpty() || txtApellidoDir.getText().isEmpty() || txtDirDir.getText().isEmpty() || txtCelDir.getText().isEmpty()
                || txtDepenDir.getText().isEmpty() || txtCorreoDir.getText().isEmpty() || txtAntigDir.getText().isEmpty() || txtHTrabDir.getText().isEmpty() || txtValorHoraDir.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Por favor, llene todos los campos", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (!pattern.matcher(txtCorreoDir.getText()).find()) {

            JOptionPane.showMessageDialog(rootPane, "El correo ingresado no es valido", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            try {
                directivos direct = new directivos();

                direct.setIdentificacion(Integer.parseInt(txtIdentDir.getText()));
                direct.setNombre(txtNombreDir.getText());
                direct.setApellido(txtApellidoDir.getText());
                direct.setDirrecion(txtDirDir.getText());
                direct.setCorreo(txtCorreoDir.getText());
                direct.setCelular(Long.parseLong(txtCelDir.getText()));
                direct.setDependencia(txtDepenDir.getText());
                direct.setAntiguedad(Integer.parseInt(txtAntigDir.getText()));
                direct.setHorasDeTrabajo(Integer.parseInt(txtHTrabDir.getText()));
                direct.setValorHora(Integer.parseInt(txtValorHoraDir.getText()));

                String mostrarInfo = direct.mostrar();
                viewDir.setVisible(true);
                viewDir.setText(mostrarInfo);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Por favor verificar el tipo de dato ingresado en el campo", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDirActionPerformed

    private void txtIdentDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentDirKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtIdentDirKeyTyped

    private void txtCelDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelDirKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtCelDirKeyTyped

    private void txtAntigDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAntigDirKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtAntigDirKeyTyped

    private void txtHTrabDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHTrabDirKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtHTrabDirKeyTyped

    private void txtValorHoraDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorHoraDirKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtValorHoraDirKeyTyped

    private void txtNombreDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDirKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtNombreDirKeyTyped

    private void txtApellidoDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoDirKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoDirKeyTyped

    private void txtDepenDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepenDirKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDepenDirKeyTyped

    private void btnOpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpeActionPerformed

        if (txtIdentOpe.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, verificar el campo de identificación", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (txtNombreOpe.getText().isEmpty() || txtApellidoOpe.getText().isEmpty() || txtDirOpe.getText().isEmpty() || txtCelOpe.getText().isEmpty()
                || txtCorreoOpe.getText().isEmpty() || txtAntigOpe.getText().isEmpty() || txtProfOpe.getText().isEmpty() || txtHTrabOpe.getText().isEmpty() || txtValorOpe.getText().isEmpty() || txtDinamico.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Por favor, llene todos los campos", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (!pattern.matcher(txtCorreoOpe.getText()).find()) {

            JOptionPane.showMessageDialog(rootPane, "El correo ingresado no es valido", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            try {
                int identi = Integer.parseInt(txtIdentOpe.getText());
                String nombre = txtNombreOpe.getText();
                String apellido = txtApellidoOpe.getText();
                String dirrecion = txtDirOpe.getText();
                long celular = Long.parseLong(txtCelOpe.getText());
                String correo = txtCorreoOpe.getText();
                int antiguedad = Integer.parseInt(txtAntigOpe.getText());
                String profesion = txtProfOpe.getText();
                int horasTrabajadas = Integer.parseInt(txtHTrabOpe.getText());
                int valorHora = Integer.parseInt(txtValorOpe.getText());

                switch (cbxTipo.getSelectedIndex()) {
                    case 1:
                        opeTecnico1 op1 = new opeTecnico1();
                        op1.setIdentificacion(identi);
                        op1.setNombre(nombre);
                        op1.setApellido(apellido);
                        op1.setDirrecion(dirrecion);
                        op1.setCelular(celular);
                        op1.setCorreo(correo);
                        op1.setTipo(cbxTipo.getSelectedItem().toString());
                        op1.setAntiguedad(antiguedad);
                        op1.setProfesion(profesion);
                        op1.setHorasTrabajadas(horasTrabajadas);
                        op1.setValor(valorHora);
                        op1.setEspecialidad(txtDinamico.getText());
                        String mostrarInfoOp1 = op1.mostrar();
                        viewOpe.setVisible(true);
                        viewOpe.setText(mostrarInfoOp1);

                        break;
                    case 2:
                        opeTecnico2 op2 = new opeTecnico2();
                        op2.setIdentificacion(identi);
                        op2.setNombre(nombre);
                        op2.setApellido(apellido);
                        op2.setDirrecion(dirrecion);
                        op2.setCelular(celular);
                        op2.setCorreo(correo);
                        op2.setTipo(cbxTipo.getSelectedItem().toString());
                        op2.setAntiguedad(antiguedad);
                        op2.setProfesion(profesion);
                        op2.setHorasTrabajadas(horasTrabajadas);
                        op2.setValor(valorHora);
                        op2.setEspecialidad(txtDinamico.getText());

                        String mostrarInfoOp2 = op2.mostrar();

                        viewOpe.setVisible(true);

                        viewOpe.setText(mostrarInfoOp2);
                        break;
                    case 3:
                        opeTecnico3 op3 = new opeTecnico3();
                        op3.setIdentificacion(identi);
                        op3.setNombre(nombre);
                        op3.setApellido(apellido);
                        op3.setDirrecion(dirrecion);
                        op3.setCelular(celular);
                        op3.setCorreo(correo);
                        op3.setTipo(cbxTipo.getSelectedItem().toString());
                        op3.setAntiguedad(antiguedad);
                        op3.setProfesion(profesion);
                        op3.setHorasTrabajadas(horasTrabajadas);
                        op3.setValor(valorHora);
                        op3.setExtra(Integer.parseInt(txtDinamico.getText()));

                        String mostrarInfoOp3 = op3.mostrar();

                        viewOpe.setVisible(true);

                        viewOpe.setText(mostrarInfoOp3);
                        break;
                    case 4:
                        opeMaster opM = new opeMaster();
                        opM.setIdentificacion(identi);
                        opM.setNombre(nombre);
                        opM.setApellido(apellido);
                        opM.setDirrecion(dirrecion);
                        opM.setCelular(celular);
                        opM.setCorreo(correo);
                        opM.setTipo(cbxTipo.getSelectedItem().toString());
                        opM.setAntiguedad(antiguedad);
                        opM.setProfesion(profesion);
                        opM.setHorasTrabajadas(horasTrabajadas);
                        opM.setValor(valorHora);
                        opM.setExtras(Integer.parseInt(txtDinamico.getText()));

                        String mostrarInfoOpM = opM.mostrar();

                        viewOpe.setVisible(true);

                        viewOpe.setText(mostrarInfoOpM);
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Por favor verificar el tipo de operario ingresado en el campo", "Warning", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Por favor verificar el tipo de dato ingresado en el campo", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnOpeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDir;
    private javax.swing.JButton btnOpe;
    private javax.swing.JComboBox cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labHE;
    private javax.swing.JTextField txtAntigDir;
    private javax.swing.JTextField txtAntigOpe;
    private javax.swing.JTextField txtApellidoDir;
    private javax.swing.JTextField txtApellidoOpe;
    private javax.swing.JTextField txtCelDir;
    private javax.swing.JTextField txtCelOpe;
    private javax.swing.JTextField txtCorreoDir;
    private javax.swing.JTextField txtCorreoOpe;
    private javax.swing.JTextField txtDepenDir;
    private javax.swing.JTextField txtDinamico;
    private javax.swing.JTextField txtDirDir;
    private javax.swing.JTextField txtDirOpe;
    private javax.swing.JTextField txtHTrabDir;
    private javax.swing.JTextField txtHTrabOpe;
    private javax.swing.JTextField txtIdentDir;
    private javax.swing.JTextField txtIdentOpe;
    private javax.swing.JTextField txtNombreDir;
    private javax.swing.JTextField txtNombreOpe;
    private javax.swing.JTextField txtProfOpe;
    private javax.swing.JTextField txtValorHoraDir;
    private javax.swing.JTextField txtValorOpe;
    private javax.swing.JTextArea viewDir;
    private javax.swing.JTextArea viewOpe;
    // End of variables declaration//GEN-END:variables
}
